### ISSUE TITLE
zRange formats

### ISSUE THREAD

**Issue by mgoda** [predis/predis#120]
nicolasff/phpredis documentation states zRange{byScore/byRank} (withscore) will return Array (key=>score, key=>score)
predis returns
Array( 0=>array(key,score), 1=>array(key,score))

Fix:
Change v0.8.3 ZSetRange.php::parseResponse line 94 from
$result[] = array($data[$i], $data[++$i]);
to 
$result[$data[$i]]=$data[++$i];

**Comment by uncle13th** [comment]
@nrk 
redis > ZRANGE salary 0 -1 WITHSCORES 
1) "jack"
2) "3500"
3) "tom"
4) "5000"
5) "boss"
6) "10086"

the result of zrange withscores is right because the members are string, but while we use integer as the  member, like the following example:

redis > ZRANGE salary 0 -1 WITHSCORES
1) "333"
2) "3500"
3) "111"
4) "5000"
5) "222"
6) "10086"

the result of zrange withscores in php is : 
[
       111 => "5000",   222=> "10086",  333=>"3500"
]

so, how can i get the right result as: 
[
      "333"=>"3500",   " 111" => "5000",   " 222"=> "10086"
]

please help, thanks!

**Comment by mgoda** [comment]
I get the same, correct result using either strings or integers:

$redis->zremrangebyscore('ztest', 0, 1000000);

$redis->zadd('ztest', '3500', '333');
$redis->zadd('ztest', '5000', '111');
$site->db->redis->zadd('ztest', '10086', '222');

$data = $redis->zrangebyscore('ztest', 0, 100000, array('withscores'=>true));
echo '<pre>'.print_r($data,true)."</pre>";
$data = $redis->zrange('ztest', 0, -1, 'withscores');
echo '<pre>'.print_r($data,true)."</pre>";

Array
(
    [333] => 3500
    [111] => 5000
    [222] => 10086
)
Array
(
    [333] => 3500
    [111] => 5000
    [222] => 10086
)
