### ISSUE TITLE
MGET over a cluster(client side sharding)

### ISSUE THREAD

**Issue by koda611** [predis/predis#149]
Are there any plans to support retrieving multiple keys over clientside sharding?  Right now an exception is thrown when i try to do that. Or is there another API I can use for this?

**Comment by janwinkler** [comment]
couldnt the client take the hashes for all the keys, check which nodes they belong to and then fire multiple mget to each node?

**Comment by andrerom** [comment]
Seems like it should be possible, reported in #520

**Comment by igauravsehrawat** [comment]
This can be solved using this information from https://redis.io/topics/cluster-spec#keys-hash-tags

> There is an exception for the computation of the hash slot that is used in order to implement hash tags. Hash tags are a way to ensure that multiple keys are allocated in the same hash slot. This is used in order to implement multi-key operations in Redis Cluster.

> In order to implement hash tags, the hash slot for a key is computed in a slightly different way in certain conditions. If the key contains a "{...}" pattern only the substring between { and } is hashed in order to obtain the hash slot. However since it is possible that there are multiple occurrences of { or } the algorithm is well specified by the following rules:

> IF the key contains a { character.
AND IF there is a } character to the right of {
AND IF there are one or more characters between the first occurrence of { and the first occurrence of }.
Then instead of hashing the key, only what is between the first occurrence of { and the following first occurrence of } is hashed.

> Examples:

> The two keys {user1000}.following and {user1000}.followers will hash to the same hash slot since only the substring user1000 will be hashed in order to compute the hash slot.
For the key foo{}{bar} the whole key will be hashed as usually since the first occurrence of { is followed by } on the right without characters in the middle.
For the key foo{{bar}}zap the substring {bar will be hashed, because it is the substring between the first occurrence of { and the first occurrence of } on its right.
For the key foo{bar}{zap} the substring bar will be hashed, since the algorithm stops at the first valid or invalid (without bytes inside) match of { and }.
What follows from the algorithm is that if the key starts with {}, it is guaranteed to be hashed as a whole. This is useful when using binary data as key names.

Solution:

You need to provide a unique identifier for set of keys inside `{}`. The data is going to be replicated anyways across the nodes.

**Comment by RedisOptimal** [comment]
Hashtag is a good way to access with single primary key, such as user info, one key with multiple dimension data.
In online shop that usually product list of search and suggestion is unexpected. The cache of product info distribution is random.
So I give a implement of mget/mset and other multiple command over redis cluster, based on redis@3.2 and jedis@3.3.0.
https://github.com/RedisOptimal/redis-cluster-support-mget
