### ISSUE TITLE
Script commands not working on first run in a transaction

### ISSUE THREAD

**Issue by TomAdam** [predis/predis#236]
If you run `SCRIPTS FLUSH` then run a script command within a transaction, Predis fails to catch the exception and re-run the transaction using EVAL rather than EVALSHA. I would be happy to provide a test that illustrates this if my description of the problem isn't clear, but I'm afraid I don't have time to work on a solution at the moment.

**Comment by nrk** [comment]
Hi @TomAdam, if you could post a small snippet with the essential bits so that I can reproduce the issue it would be a great help!

**Comment by TomAdam** [comment]
I'm currently on holiday till the 30th. Will get you something soon after that point.

**Comment by nrk** [comment]
Thanks and enjoy your holiday! :-)

**Comment by nrk** [comment]
I finally had some time to investigate this issue and found that problem lies in `-NOSCRIPT` errors being returned by Redis inside the array response to `EXEC` (when the transaction has been already "finalized") and not when the `EVALSHA` is sent to the server while still inside the context of a `MULTI ... EXEC` block. If the transaction has been already finalized, there's no way to issue a `DISCARD` command thus making it impossible to safely re-run it.

This issue is hard to fix in a consistent way unfortunately, the only solution to make it really safe would be to always fall back to using `EVAL` for script commands at the cost of losing the optimization of `EVALSHA`. This could be easily implemented with an ad-hoc class that extends `Predis\Transaction\MultiExec`:

```php
class SafeMultiExec extends Predis\Transaction\MultiExec
{
    public function executeCommand(Predis\Command\CommandInterface $command)
    {
        if ($command instanceof Predis\Command\ScriptCommand) {
            $arguments = $command->getEvalArguments();
            $command = $this->client->createCommand('EVAL');
            $command->setRawArguments($arguments);
        }

        return parent::executeCommand($command);
    }
}
```

Here you can see a quick snippet to see it in action:

```php
class TestCommand extends Predis\Command\ScriptCommand
{
    public function getScript()
    {
        return "return 'FOOBAR'";
    }
}

$client = new Predis\Client('tcp://127.0.0.1:6379', [
    'profile' => function ($options) {
        $profile = $options->getDefault('profile');
        $profile->defineCommand('myscriptcommand', 'TestCommand');

        return $profile;
    }
]);

$client->script('flush');

$response = (new SafeMultiExec($client))->execute(function ($tx) {
    $tx->myScriptCommand();
});

var_dump($response);

/*
array(1) {
  [0]=>
  string(6) "FOOBAR"
}
*/
```

I'm not sure about changing `Predis\Transaction\MultiExec` to make it the default behavior, but this should be definitely documented somewhere (we still don't have such docs :disappointed:). A bit of feedback from other developers would be great...

**Comment by TomAdam** [comment]
Sorry I didn't get back to you, holiday was a little too good! My preferred approach would be to always use EVAL within a transaction, but allow this functionality to be overridden by a parameter in the command class that gives the following options:

- default - EVAL in transactions, EVALSHA outside
- force EVAL
- force EVALSHA

I'd then add a class that runs SCRIPT LOAD for all registered commands (or a subset) that can be used by a cache warmer or CLI task or similar (within a SF bundle for example).

I'd love to offer to do this if you are interested, but realistically my time is a bit limited at the moment. Might be able to look at it around the start of next month?
