### ISSUE TITLE
Predis not Serializing Objects

### ISSUE THREAD

**Issue by stephenlb** [predis/predis#29]
It appears that this fails:

```
// Set Array
$redis->set( 'key', array(1,2,3) );
```

This is unanticipated with such a complete library.  Where is the best place to put an object/array serializer for all Reids Commands?

**Comment by joeyhub** [comment]
Hello,

I don't get what is with the profile thing in an OO world.

Why not provide a proxy class over the client class to intercept all the get set calls and serialize as necessary?

abstract class Predis\ProxyClient extends Predis\Client
   abstract method decode(string)
   abstract method encode(mixed)

   method get(string key)
       return $this->decode(parent::get(key))

If you separated your connection class this would work allowing difference client types for one connection.

Thanks.

**Comment by nrk** [comment]
@joeyhub you can indeed extend `Predis\Client` and implement both `get()` and `set()` methods to make them serialize / deserialize stuff, but that solution wouldn't work with pipelines, transactions and clustering due to how Predis is internally structured as these features work directly against the underlying connection.

**Comment by ryr** [comment]
what about optional (like prefixing) variant to autoserialize (jsonify) all values, stored in redis?
```
$options = ['serialize' => 'json']
```

**Comment by tillkruss** [comment]
Data serialization and compression will be added in #1084.
