### ISSUE TITLE
Implement `WAIT` command

### ISSUE THREAD

**Issue by tPl0ch** [predis/predis#298]
Hello,

currently we want to use the `WAIT` - http://redis.io/commands/WAIT - command to increase data safety for certain write requests in the `redis-cluster` mode. Since `WAIT` is not implemented, we were trying to use a raw command:

``` php
$redisSuccess = $this->redis->set($key, $value, 'ex', $ttl, 'nx');
// Wait for writes to propagate through the cluster - TTL of 0.5 seconds
$slavesReached = (int) $this->redis->executeRaw(['WAIT', 2, 500]);
if ($slavesReached < 1) {
    throw new ClientException("Couldn't distribute write to slaves");
}
```

Unfortunately it tries to get a `Slot` for the `WAIT` command and fails with:
`Cannot use 'WAIT' with redis-cluster.`

Can we somehow manage to get the `WAIT` command working within the current architecture, by i.e. supplying an own `ClusterStrategy`?

Thanks in advance,
Thomas

**Comment by tPl0ch** [comment]
@nrk 
> When using a client configured in cluster mode the only restriction is that all of the writes ... must be directed to the same slot

Hmm, this is dramatically limiting the usefulness of `WAIT` in a cluster setup. You have a set of key/value pairs that you want to ensure to have reached a majority of nodes, even if they are routed to different slots, don't you think?

**Comment by nrk** [comment]
@tPl0ch the problem when using a cluster setup is that `WAIT` must be sent to each node interested by a write operation and, as far as I understand, this is valid for redis-cluster too. Predis cannot do this asynchronously so the first `WAIT` will block until acknowledgement / timeout before sending the next one and so forth. After that, there's the problem of how to handle different acknowledgement outcomes among the various "slots" that are target of writes.

**Comment by tPl0ch** [comment]
@nrk Then it will be time to leverage coroutines and/or promises to handle cluster-wide commands in a non-blocking way :computer:

**Comment by nrk** [comment]
@tPl0ch that would still need asynchronous I/O, something that doesn't really fit in the way Predis is designed. An hack would be getting the underlying stream resources of each connection, set them as non-blocking and go with `stream_select()` (basically you'd want to embed [reactphp/event-loop](https://github.com/reactphp/event-loop))... at least responses to `WAIT` are really simple so there's no real need for a streaming parser for the RESP protocol. The same could be done using [Predis\Async](https://github.com/nrk/predis-async) (it doesn't use coroutines or promises but it's still a full-fledged non-blocking implementation) but then again it's a kind of specialized use case, so it'd probably be a better idea for now to have such a thing implemented as a separate component instead of having it shipped in Predis.

By the way for simple use cases like the need to acknowledge the previous write operation using redis-cluster (just like your initial example), in Predis v2.0 it will be possible to do this:

```php
$redis->set($key, $value);
$slavesReached = $redis->getClientBy('key', $key)->wait(2, 100);
```
