### ISSUE TITLE
Use Sentinel without reading from slaves

### ISSUE THREAD

**Issue by dingchaolu** [predis/predis#383]
It seems using Sentinel (https://github.com/nrk/predis/blob/v1.1/examples/replication_sentinel.php) automatically forces reads to go to the slaves. Is there a way to make all reads go to master while using Sentinels?

**Comment by nrk** [comment]
There's no clean way (*) to do this right now, but I think it makes perfect sense to turn this behaviour configurable by the user.

(*) the dirty way requires a convoluted configuration of the client to pass the instance of a subclass of `Predis\Replication\ReplicationStrategy`... if you are interested I can post a sample showing how to do it.

**Comment by chelovekov** [comment]
Hello!
I am interested with "dirty way" to fix this problem. I have several ideas how to do it, but I don't like It. 
Can you show sample of code with the least "dirty" way?

**Comment by jaugustin** [comment]
@chelovekov 

We did a dirty fix this way on our project override the client 

```php
class PredisClient extends Client
{
    /**
     * @inheritDoc
     */
    public function executeRaw(array $arguments, &$error = null)
    {
        // force connection to use master
        $this->switchToMaster();

        return parent::executeRaw($arguments, $error);
    }

    /**
     * @inheritDoc
     */
    public function executeCommand(CommandInterface $command)
    {
        // force connection to use master
        $this->switchToMaster();

        return parent::executeCommand($command);
    }

    /**
     *  force the redis connection to use master
     */
    public function switchToMaster()
    {
        if ($this->connection instanceof ReplicationInterface) {
            $this->connection->switchTo('master');
        }
    }
}
```

@nrk if your "dirty" way is different I would be happy to know how you did it, and of course having it handled by a client option would be even better.

**Comment by gyrter** [comment]
Hello, nrk. I'm very interesting about this scenario too. Can you post configuration of the client?

**Comment by nrk** [comment]
I have not tested the following solution but it should work perfectly fine (based on Predis 1.1):

```php
class CustomReplicationStrategy extends \Predis\Replication\ReplicationStrategy
{
    protected function getReadOnlyOperations()
    {
        return [];
    }
}

$client = new \Predis\Client($sentinels, [
    'service'   => $service,
    'aggregate' => function () {
        return function ($sentinels, $options) {
            $replication = new \Predis\Connection\Aggregate\SentinelReplication(
                $options->service,
                $sentinels,
                $options->connections,
                new CustomReplicationStrategy()
            );

            return $replication;
        };
    },
]);
```

As you can see it's a bit convoluted. You extend the default replication strategy, which defines which commands peform read and write operations, and override its `getReadOnlyOperations()` method to return an empty array: this basically instructs the client to consider all commands as write operations so that the client will always use the master node (this is the dirty part of the solution but it doesn't really have any other side effect so it's OK from a practical point of view). Then you configure the client to make it use your own replication strategy for the sentinel backend, but instead of the usual `replication` option you must use the `aggregate` option which expects a callable that returns the actual connection instance.

I'm thinking about adding a method like `SentinelReplication::useSlavesForReads(bool $flag)` to make this easier.

**Comment by basos9** [comment]
Hello, I think this is an important feature for cases when Redis is used for volatile "persistent" data, like session data (in contrast with volatile "temporary" data, like cache data ). It could be more convenient, appart from the method, to have this configured by a property . e.g:
```
$sentinels = ['tcp://10.0.0.1', 'tcp://10.0.0.2', 'tcp://10.0.0.3'];
$options = [
    'replication' => 'sentinel',
    'service' => 'mymaster',
    'parameters' => [
        'useSlavesForReads' => false
    ],
];

$client = new Predis\Client($sentinels, $options);
```

When we store user session information in redis in order to have this shared by multiple backend servers, we consider this data to be "persistent" in the sense that once the data is acknowledged by the redis system we consider this stable.  Also redis replication is asynchronous by design [1] (i.e. the master does not wait for the writes to be acknoledged by slaves) 

So imagine the scenario for an application running in multiple active application servers using predis with a sentinel setup with one master and many slaves replicating to master:

1. Application Server 1 (AS1) creates a session object and successfully stores it to master (this is a write operation) - in response to user login action
1.1 Redis master starts replication to slaves
2. AS2 reads session object, predis randomly selects one redis slave isntance (e.g. Slave1) and reads a stale session - in response to user read data
3. Redis Slave1 acknowledges master data, with some latency due to network load


So in step 2 the application reads the stale session object (either a non existing object). Note that this is a possible scenario in **normal** operation (though rare), not in a failover situation. (In the later case we could agree that since failovers are expected to happen more rarely, that we don't have a problem to read stale data).


--- 

[1] Quote from https://redis.io/topics/replication

> Redis uses by default asynchronous replication, which being low latency and high performance, is the natural replication mode for the vast majority of Redis use cases. However Redis replicas asynchronously acknowledge the amount of data they received periodically with the master. So the master does not wait every time for a command to be processed by the replicas, however it knows, if needed, what replica already processed what command.
