### ISSUE TITLE
Redis Cluster with multiple master and replica nodes

### ISSUE THREAD

**Issue by Abam** [predis/predis#392]
As described in [the official redis documentation Redis Cluster master-slave model](http://redis.io/topics/cluster-tutorial), it is possible to have a cluster with master-slave model.

> so that the final cluster is composed of A, B, C that are masters nodes, and A1, B1, C1 that are slaves nodes, the system is able to continue if node B fails.

But it seems that is not supported by predis configuration. We have to choose between either a cluster model or a master slave model with only one master. The code in [Client.php](https://github.com/nrk/predis/blob/v1.1/src/Client.php#L123) seems to confirm it (if replication is choosen, the else case dealing with cluster is never reached).

Any plan on supporting this configuration ?

Edit: After having a deep dive into https://github.com/nrk/predis/blob/v1.1/src/Connection/Aggregate/PredisCluster.php it seems that if useClusterSlots is true, the client will be able to update slots and therefore use slaves if master fail. Isn't it ?

**Comment by nrk** [comment]
This is indeed not yet supported by Predis. Slaves are ignored by the client when it [fetches the slot map](https://github.com/nrk/predis/blob/v1.1.1/src/Connection/Aggregate/RedisCluster.php#L260-L272) from one of the Redis nodes, furthermore it is not possibile to specify them manually via the client's configuration (but this may change with Predis 2.0 thanks to some internal but breaking changes to support a `role` parameter).

When `useClusterSlots` is set to `TRUE` (which is the default behaviour) this is a actually a minor issue since redis-cluster takes care of electing a new master from the pool of slaves connected to a dead master, so this feature would useful mostly to offload master nodes by redirecting read operations to their slaves (like it happens when using replication).

**Comment by Abam** [comment]
Ok, thanks for the reply. So I can rely on the userClusterSlots parameter for predis v1.1.

**Comment by nrk** [comment]
@Abam my plans anyway are to make Predis aware of slaves in a redis-cluster configuration in the future, so I'll just leave this issue open as a reminder. Thanks.

**Comment by binwiederhier** [comment]
Any movement on this? Anything that can be done to help with this?

**Comment by binwiederhier** [comment]
I briefly looked into implementing cluster support for your library, but it seems to be non-trivial (at least to me). Thanks for all the work on it. It works wonderfully in a non-clustered environment. 

For my redis topology (3 masters, 3 slaves), I'll have to go with [phpredis](https://github.com/phpredis/phpredis/blob/develop/cluster.markdown) for now, since it has cluster support for multiple masters.

**Comment by nrk** [comment]
@binwiederhier I'm not sure what do you mean. Redis cluster is fully supported, it's just that slaves cannot be used by Predis to distribute reads among them.

**Comment by binwiederhier** [comment]
My apologies, maybe I misunderstood then, or I was doing it wrong then. I was constantly getting `MOVED ...` responses back from my cluster and Predis would not automatically handle them. I will give it another shot. Thanks for the quick response.

**Comment by nrk** [comment]
@binwiederhier well yes you need to tell the client you are about to connect to Redis instances managed by redis-cluster, [see here](https://github.com/nrk/predis#cluster).

**Comment by binwiederhier** [comment]
That's what I was doing:

```
return new Predis\Client($serverUris, array( // list of tcp://...
   'exceptions' => true,
   'cluster' => 'redis'
));
```

As I said, I will investigate more, maybe I was doing something wrong.

**Comment by nrk** [comment]
The configuration appears to be correct (you can also avoid setting `exceptions`, that's the default). Please make sure that `get_class($client->getConnection())` returns `Predis\Connection\Aggregate\RedisCluster`, and if you still get `-MOVED` responses from Redis despite that please open a new issue with more details because that's definitely not the normal behaviour.

**Comment by binwiederhier** [comment]
It works like a charm now. My apologies for the confusion. My problem was that I was accidentally only passing one master in the $serverUris array.

**Comment by jose9r** [comment]
hello, when will be available the possibility of reading on the slave nodes ?

**Comment by nrk** [comment]
@jose9r sorry no ETA about that, but I'm always willing to accept quality contributions from devs.
