### ISSUE TITLE
[RFE] use phpiredis when available

### ISSUE THREAD

**Issue by remicollet** [predis/predis#397]
For discussion.

**phpiredis** 1.0.0 is released \o/

```
new Predis\Client(['host' => '127.0.0.1', 'port' => 6379]);
```
Above default usage will not use phpiredis which give great performance improvment.

To use phpiredis, need to use (perhaps I've missed something)

```
new Predis\Client(['host' => '127.0.0.1', 'port' => 6379], 
    ['connections' => ['tcp' => 'Predis\\Connection\\PhpiredisSocketConnection']]);
```

I think it could make sense to use PhpiredisSocketConnection by default, if no 'connections' given, and if the extension is available.

At least, perhaps some enligth in the documentation about this (I have to search in the code to find the correct way to use phpiredis).

**Comment by nrk** [comment]
Your snippet is correct, but actually the configuration required to make Predis use phpiredis is [written in the README](https://github.com/nrk/predis/blob/v1.1/README.md#customizable-connection-backends). Maybe we should make that paragraph more immediatly accessible with a direct link to it at the top of the README, instead of having a link to the repository of phpiredis. By the way in most cases it's better to use `Predis\Connection\PhpiredisStreamConnection` since it uses PHP's native streams, while `Predis\Connection\PhpiredisSocketConnection` requires `ext-socket`.

Anyway in the past I considered the idea of letting the client automatically prefer the phpiredis-based connection backend when the extension is loaded in PHP, but at that time I decided to avoid doing that due to possible differences in the behaviour of the two backends and even more so now that we have SSL supported by the default connection but we can not implement it for the phpiredis-based one.

**Comment by nrk** [comment]
In the end we'll stick with the current behaviour of **not** loading a [phpiredis](https://github.com/nrk/phpiredis) based connection backend by default when the extension is loaded, users should specify which connection backend to use explicitly. That said I recently came up with an idea for a nicer and less cumbersome way to configure the client to use the two backends based on phpiredis, see #651 for details (planned for v2.0).
