### ISSUE TITLE
Sentinel timeout is too low

### ISSUE THREAD

**Issue by jhnlsn** [predis/predis#424]
Documentation says that the default timeout is 5 seconds, however, for Sentinel it is set to 100ms as seen here:

https://github.com/nrk/predis/blob/v1.1/src/Connection/Aggregate/SentinelReplication.php#L75

having issues with an array of options so currently not able to set the timeout value as part of the parameters.

**Comment by nrk** [comment]
The timeout for sentinel servers is lower than the timeout for actual redis servers because you don't really want your application to hang just because one of the sentinels is down or slow to respond, the whole purpose of sentinels is to provide better HA after all. If you want to override that value, you can just add a different `timeout` value to each sentinel parameters set. This could be improved to a certain extent, but it was not possible to do so in the current major release branch without introducing breaking changes.
