### ISSUE TITLE
Transaction with CAS partially executed despite Exception thrown

### ISSUE THREAD

**Issue by Berbe** [predis/predis#437]
Using a Redis transaction with Check And Set the following way:
```
$options = array(
	'cas' => true,
	'watch' => array(
		[...]
	),
	'retry' => 3
);
$transactionResults = $redis->transaction($options, function($tx) use ($foo, $bar) {
	$improperNumber;
        [...]

	$tx->multi();
	$tx->hset('test:'.$foo, 'foo', $foo);
	$tx->zadd('test:'.$bar, 0, $bar);
	$tx->zadd($foo, $improperNumber, $bar);
        [...]
});
```
I was thrown an Exception at:
```
PHP Fatal error:  Uncaught exception 'Predis\Response\ServerException' with message 'ERR value is not a valid float' in [...]
Stack trace:
#0 Predis/Client.php(477): Predis\Transaction\MultiExec->execute(Object(Closure))
#1 Predis/Client.php(401): Predis\Client->createTransaction(Array, Object(Closure))
#2 Predis/Client.php(461): Predis\Client->sharedContextFactory('createTransacti...', Array)
#3 script.php(182): Predis\Client->transaction(Array, Object(Closure))
#4 {main}
  thrown in Predis/Transaction/MultiExec.php on line 408
```
However, the keys appearing before the invalid line (here HSET and the first ZADD) were added to my Redis database, while it was expected the atomicity of the transaction, which should be guaranteed by design, would prevent anything to be changed.

What is going on?

**Comment by nrk** [comment]
Which version of Predis and Redis?

**Comment by Berbe** [comment]
Redis v3.2.8 64 bits (Debian stable backports package v3:3.2.8-2~bpo8+1)
Predis v1.1.1

**Comment by Berbe** [comment]
Any news on this?
Have you been able to reproduce the problem?

**Comment by nrk** [comment]
Hi @Berbe,

In the end there was nothing strange going on here, but let me explain by reproducing everything by using your snippet (just simplified by removing variables) inside an interactive shell and see the result:

```
>>> $client = new Predis\Client();
=> Predis\Client {#2359}

>>> $options = ['cas' => true, 'watch' => ['foo'], 'retry' => 3];
=> [
     "cas" => true,
     "watch" => [
       "foo",
     ],
     "retry" => 3,
   ]

>>> $result = $client->transaction($options, function($tx) {
...     $improperNumber = "ohnoes";
... 
...     $tx->multi();
...     $tx->hset("test:foo", 'foo', 'foo');
...     $tx->zadd("test:bar", 0, 'bar');
...     $tx->zadd('foo', $improperNumber, 'bar');
... });
Predis/Response/ServerException with message 'ERR value is not a valid float'

>>> $client->keys("*");
=> [
     "test:bar",
     "test:foo",
   ]
```

Indeed both `HSET` and the first `ZADD` were executed by the transaction. Now let's see what happens with `redis-cli` trying to do the same on an empty database:

```
127.0.0.1:6379> MULTI
OK
127.0.0.1:6379> HSET test:foo foo foo
QUEUED
127.0.0.1:6379> ZADD test:bar 0 bar
QUEUED
127.0.0.1:6379> ZADD foo ohnoes bar
QUEUED
127.0.0.1:6379> EXEC
1) (integer) 1
2) (integer) 1
3) (error) ERR value is not a valid float
127.0.0.1:6379> KEYS *
1) "test:bar"
2) "test:foo"
```

As you can see the behaviour is exactly the same and is the expected one [as described on the Redis documentation](https://redis.io/topics/transactions#why-redis-does-not-support-roll-backs). If Redis returns a `+QUEUED` response for a command executed inside a `MULTI` ... `EXEC` block it means that it was queued succesfully so there's no reason for the transaction to fail.

Having said that, Predis by default throws `Predis\Response\ServerException` exceptions when it detects a `-ERR` response in the array of responses returned by `EXEC`. If you want to override this behaviour you can simply initialize the transaction block using `"exceptions" => false` in the `$options` array.

To be honest for v2.0 I'm thinking of making the behaviour of `"exceptions" => false` the default for both abstractions of transactions and pipelines even when the parent client instance is configured to throw exceptions, but I'm still investigating this.

**Comment by Berbe** [comment]
Oh wow, that is an oldie.

Thanks for the detailed answer, and having avoided an "RTFM" one (which, to be honest, would be justified there :oD).

Odd design decision, and the arguments thrown to back it up seem sketchy. What a circumvoluted way of actually saying "all that matters for Redis is speed, hence I cannot care less about safety nets"...
Redis is definitely more on the cache side of things than on the DB one with such major hiccups.

The new default might be handy indeed, but I would understand if it were seen as cosmetic anyway (maybe a dedicated Exception type would be a good compromise, even though it would be already breaking flows based on this precise type?). I know changing defaults during the lifecycle of a product is usually regarded as endangering backwards compatibility and/or alienating users.

Thanks for having taken the time to reply.

**Comment by nrk** [comment]
> Oh wow, that is an oldie.

Better late than never :wink: 

> Odd design decision, and the arguments thrown to back it up seem sketchy. What a circumvoluted way of actually saying "all that matters for Redis is speed, hence I cannot care less about safety nets"...

I think the confusion comes from the decision of having `MULTI` ... `EXEC` commonly referred to as _transactions_ when the only guarantee is about the atomicity of the __execution__ of commands queued inside a `MULTI` ... `EXEC` block. Even `DISCARD` is not a rollback, it's just a way to clear the commands previously queued by Redis. In a sense `EVAL` + `EVALSHA`  with Lua scripts can be a better solution than `MULTI` ... `EXEC` in various scenarios: you still get the same guarantee about atomicity during the execution of their bodies but you don't need check-and-set (thus avoiding network roundtrips) and you can even implement some sort of custom rollback logic on the server side if needed.

> Redis is definitely more on the cache side of things than on the DB one with such major hiccups.

It really depends. It's indeed a major hiccup if trying to do things the same way as they are usually done when using a RDBMS.

> The new default might be handy indeed, but I would understand if it were seen as cosmetic anyway (maybe a dedicated Exception type would be a good compromise, even though it would be already breaking flows based on this precise type?). I know changing defaults during the lifecycle of a product is usually regarded as endangering backwards compatibility and/or alienating users.

Still not sure on how I'm going to handle this but what's sure is that the current behaviour will remain the same for v1 in both patch and minor releases, this change is planned for v2 (the next major release currently in development) which is full of breaking changes anyway.

> Thanks for having taken the time to reply.

It was still useful to me because, truth to be told, I just discovered a bug thanks to your snippet :smile:

Initializing `Predis\Transaction\MultiExec` with `"cas" => true` and **no check-and-set operations** before `$tx->multi()` does not execute subsequent commands inside `MULTI` ... `EXEC` but they are executed like plain commands on Redis. If there's at least one check-and-set operation then there's no problem. In fact tests cover `"cas" => true` only with actual check-and-set operations or a totally empty block.

This doesn't change the behaviour described in my answer and the end result would be exactly the same even without this bug in Predis.
