### ISSUE TITLE
Redis-cluster documentation seems incorrect

### ISSUE THREAD

**Issue by sysadmin1139** [predis/predis#513]
We're using predis version 1.1.1 in PHP7.1, on Ubuntu 14.04, and are attempting to connect to an AWS ElasticCache Redis cluster in HIPAA mode. So the cluster is running:

* Redis 3.2.6
* Requiring TLS connections
* Requiring authentication
* Cluster-mode
* Replicated

This should be handled by predis, but it seems to not be the case. When we configure our connection like this:

```php
$connect = "tls://aws-ec-host:6379";
$options = [
  'cluster'    => 'redis',
  'parameters' => [
    'password' => 'secrets',
    'ssl'      => [
      'verify_peer' => 'true'
    ]
  ]
];
$red_client = new Predis\Client($connect, $options);
```

Where the connection string is a string, it will correctly connect. However, some `GET` and `SET` operations are throwing exceptions our code is getting, referencing `MOVED` responses. Given how redis clusters work, and our node count, we're getting them about as often as what you'd expect for a keyslot on a node other than the one we're connecting to. It is *definitely* connecting over TLS and authenticating, which is great. Apparently predis isn't aggregating as it should.

However, the documentation states:

> Along with Redis 3.0, a new supervised and coordinated type of clustering was introduced in the form of redis-cluster. This kind of approach uses a different algorithm to distribute the keyspaces, with Redis nodes coordinating themselves by communicating via a gossip protocol to handle health status, rebalancing, nodes discovery and request redirection. In order to connect to a cluster managed by redis-cluster, the client requires a list of its nodes (not necessarily complete since it will automatically discover new nodes if necessary) and the cluster client options set to redis:

And gives as an example:
```php
$parameters = ['tcp://10.0.0.1', 'tcp://10.0.0.2', 'tcp://10.0.0.3'];
$options    = ['cluster' => 'redis'];

$client = new Predis\Client($parameters, $options);
```
Following this advice, if we adjust our connect string to 
```php
$connect = [ "tls://aws-ec-host:6379" ];
```
The Client creation fails with:

> Cannot use 'CLUSTER' with redis-cluster

The documentation suggests this should work, but it clearly doesn't.

**Comment by nrk** [comment]
Just tested using your snippet and using `$connect = [ "tls://aws-ec-host:6379" ];`

```
>>> $cluster = new Predis\Client($connect, $options);
=> Predis\Client {#2362}
>>> $cluster->getConnection();
=> Predis\Connection\Aggregate\RedisCluster {#2359}
```

So the client is using the redis-cluster backend as expected and documented, there's no issue here.

Actually you have a very different problem as hinted by the following line:

> Cannot use 'CLUSTER' with redis-cluster

This means that you are  trying to use that client instance to send one of the variants of the `CLUSTER` command to Redis but this won't work because these commands do not have an associated key to be hashed in order to calculate a slot and so they cannot be routed to a specific node in the cluster.

In such cases you can work around this by literally fooling the client to use a random slot (or one of your choice depending on you needs). For the following example I'm going to use `CLUSTER NODES` as an example, but the same approach can be used for any command that isn't directly supported for the above mentioned reason:

```php
// Create a client instance with the parameters and options for your cluster.
$cluster = new Predis\Client($connect, $options);

// Create a command instance for the `CLUSTER SLOT` command.
$command = \Predis\Command\RawCommand::create("CLUSTER", "NODES");

// Assign a random slot to the command, this one will be used by the client to route
// it to the associated node in the cluster. redis-cluster is partitioned into 16384 slots.
$command->setSlot(mt_rand(0, 16383));

// Once $command has a slot associated, the client can properly route it.
$response = $cluster->executeCommand($command);
```

You can easily wrap the relevant parts in a utility function or method if you need to reuse this in various places through your application. We are investigating how to improve this for Predis v2.0 (being a major release, breaking changes will be allowed).
