### ISSUE TITLE
Add support for sentinel authentication

### ISSUE THREAD

**Issue by dzoeteman** [predis/predis#594]
In late 2018 sentinel got support for authentication. Currently predis does not support this due to d92f31dc66cd63c1f150891f2c40da75044df000. 

See: https://github.com/antirez/redis/commit/fa675256c127963c74ea68f8bab22ef105bada02

**Comment by nrk** [comment]
I'm assigning it for v2.0 for now but maybe this can be implemented as a bugfix in v1.1. Right now I'm just not sure that [removing this line](https://github.com/predis/predis/commit/d92f31dc66cd63c1f150891f2c40da75044df000#diff-e55f11b907debe0b57a114d0c38dc563R245) would be enough for a proper support at least regarding the configuration bits of the client.

**Comment by nrk** [comment]
Fixed in 2e76410, fix will be shipped with v1.1.5 in a few days.

Please note that, **at least for now**, the common password used by sentinels (see `requirepass` in `sentinel.conf`) should be set explicitly with a `password` set for each sentinel, even if this password is the same. Passing it using the global `parameters` client options is not a good idea because these parameters are the **defaults** applied to **every** connection created by Predis, this would mean that the same password would also be used when connecting to actual Redis (and that was the reason behind d92f31d, see #346). We really need to find a way to specify a common password for sentinels so that it's handled in a different way from passwords for Redis nodes.

**Comment by nrk** [comment]
I'm re-opening this issue as I had to revert the change implemented in v1.1.5 and release v1.1.6. There was a bug as pointed out in #658 and after reviewing the mistake I noticed another bug only waiting to be discovered (we need to apply the password also [when a new sentinel is discovered](https://github.com/predis/predis/blob/v1.1.6/src/Connection/Aggregate/SentinelReplication.php#L301-L304) by asking for an updated list from sentinels themselves.

**Comment by BridgeTrollPW** [comment]
Hey there, is there currently a workaround for sentinels using passwort authentication?

**Comment by tillkruss** [comment]
@BridgeTrollPW @dzoeteman feel free to chime in an test #739.
