### ISSUE TITLE
Cannot use 'HSET' with redis-cluster.

### ISSUE THREAD

**Issue by intashish** [predis/predis#602]
**Env:**
Predis: 1.0.3
redis: 3.0.6
php: 5.4
Framework : codeigniter(2.1.0)

**ERROR:**
Predis\NotSupportedException: Uncaught exception 'Predis\NotSupportedException' with message 'Cannot use 'HSET' with redis-cluster.' in /var/www/domain.name/application/libraries/predis-1.0/src/Connection/Aggregate/RedisCluster.php:299
in Predis\Connection\Aggregate\RedisCluster::getConnection called at /var/www/domain.name/application/libraries/predis-1.0/src/Connection/Aggregate/RedisCluster.php (470)
in Predis\Connection\Aggregate\RedisCluster::executeCommand called at /var/www/domain.name/application/libraries/predis-1.0/src/Client.php (326)
in Predis\Client::executeCommand called at /var/www/domain.name/application/libraries/predis-1.0/src/Client.php (310)
in Predis\Client::__call called at /var/www/domain.name/application/libraries/REST_Controller.php (937)
in Predis\Client::hset called at /var/www/domain.name/application/libraries/REST_Controller.php (937)

**Description:**
I am using a Redis cluster. I am not able to figure out why this error is coming. 
I am new to Redis. Please help

**Comment by nrk** [comment]
Hi @intashish, to be honest I can't think of a reason why you are getting this error given that `HSET` was indeed [allowed to be used with redis-cluster](https://github.com/nrk/predis/blob/v1.0.3/src/Cluster/ClusterStrategy.php#L153) since the start with any release of Predis 1.0.

Could you provide a basic script with no dependencies (aside from Predis) that reproduces this issue?

**Comment by nrk** [comment]
After further inspection I can confirm that `HSET` does work correctly when using redis-cluster since Predis v1.0.0.

That said I was able to reproduce the error reported in your issue by calling `HSET` without arguments (which is wrong):

```
>>> $cluster = new Predis\Client($parameters, $options);
=> Predis\Client {#2358}
>>> $cluster->hset();
Predis/NotSupportedException with message 'Cannot use 'HSET' with redis-cluster.'
```

I admit the exception message is a bit misleading in this case because `HSET` is indeed supported but trying to call it without passing any argument means that the underlying strategy cannot find a key (which is used to calculate the hash and route a command to the appropriate node) and bails thinking that the command cannot be used when Predis is configured to connect to a cluster.

Anyway there's no issue with using `HSET` with redis-cluster.

**Comment by hanweimin** [comment]
hi,  I have a problem with the redis-cluster connection. Can you see a configuration option here for my reference

thanks
