### ISSUE TITLE
Don't stick on master in replication mode.

### ISSUE THREAD

**Issue by Fred07** [predis/predis#633]
The situation happens with replication mode, and application running as a daemon process, for example: [ReactPHP](https://reactphp.org/)

the original behavior of `MasterSlaveReplication` in a process is to stick on master connection after a write-command send, even if it's a read-only command actually.

mostly apps like http server, it's fine because every new request(process) would start a new predis instance with slave connection if it's read-only.

but that is unacceptable for my situation which I wish it still using the connection according to the read/write command no matter what commands just send, because the process is never shutdown.

So my suggestion is changing the behavior of `Predis\Connection\Aggregate\MasterSlaveReplication.php:getConnection()`

I draft it and simplify from the old one like below:

```php
public function getConnection(CommandInterface $command): NodeConnectionInterface
{
    // Use slave if command is readonly
    if ($this->strategy->isReadOperation($command) && $slave = $this->pickSlave()) {
        $this->current = $slave;
    } else {
        $this->current = $this->getMasterOrDie();
    }

    return $this->current;
}
```

this will find an available connection every time a new command comes in.

but not to completely replace original behavior, maybe we can add a flag like  `bool $stick` , for user to decide to active this feature or not.

and that would be like:

```php
public function getConnection(CommandInterface $command): NodeConnectionInterface
{
    // stick mode and current is master
    if ($this->stick && $this->current === $master = $this->getMasterOrDie()) {
        return $master;
    }

    // Use slave if command is readonly
    if ($this->strategy->isReadOperation($command) && $slave = $this->pickSlave()) {
        $this->current = $slave;
    } else {
        $this->current = $this->getMasterOrDie();
    }

    return $this->current;
}
```

**Comment by nrk** [comment]
Hi @Fred07,

The first issue that comes to mind with using this approach is that it would completely break `MULTI` / `EXEC` as you cannot hop from one node to another while inside a transaction: you **must** stick to the same node hit by `MULTI` as you progress with the transaction and it must be the master node simply because it's not possible to guess beforehand if you will have a write operations between `MULTI` and `EXEC` (well you **might** know in your own specific application, but this cannot be generalized). I'm pretty sure there are more corner cases.

Personally, this is enough to reject such a feature.

That said, if you problem with the current behaviour is related to long running processes then nothing stops you from issuing a [`Predis\Connection\Aggregate\MasterSlaveReplication::reset()`](https://github.com/predis/predis/blob/v1.1.2/src/Connection/Aggregate/MasterSlaveReplication.php#L95-L101) at the most appropriate point in the flow of your application. Doing so will force the aggregate connection to pick a new node (either a master or replica, on the next command.

And if you do need to do that on each command, then it would probably be better to roll your own aggregate connection by subclassing `Predis\Connection\Aggregate\MasterSlaveReplication` with something along these lines:

```php
use Predis\Connection\Aggregate\MasterSlaveReplication;
use Predis\Command\CommandInterface;

class MyCustomReplication extends MasterSlaveReplication
{
    public function getConnection(CommandInterface $command)
    {
        $this->reset();
        $response = parent::getConnection($command);

        return $response;
    }
}
```

**Comment by Fred07** [comment]
It is good reason to keep in master connection in `MULTI` and `EXEC` and more. Thanks for the explanation.
