### ISSUE TITLE
Basic async support for map-reduce (without event-loop)

### ISSUE THREAD

**Issue by halaei** [predis/predis#636]
**Is your feature request related to a problem? Please describe.**
Extending predis pipeline, I was able to simultaneously send the same command to multiple Redis instances and wait for the responses and process them in PHP to form the final result. It is basically a map-reduce model. I am wondering if you can officially add such a feature to predis as well. Please note that here by "async" I don't mean to work on top of some event loop library. I am not entirely sure how efficient my code is. By predis support being back again, I hope for a better implementation and further support here.

**Describe the solution you'd like**
Here is my code and an example test:
```php
class TwoStepPipeline extends Pipeline
{
    /**
     * @var ConnectionInterface
     */
    protected $waitingConnection;

    /**
     * @var \SplQueue
     */
    protected $waitingCommands;

    /**
     * Flush the queue without waiting for the responses.
     *
     * @inheritdoc
     */
    protected function executePipeline(ConnectionInterface $connection, \SplQueue $commands)
    {
        if (! $this->waitingCommands) {
            $this->waitingCommands = new \SplQueue();
        }

        foreach ($commands as $command) {
            $connection->writeRequest($command);
            $this->waitingCommands->enqueue($command);
        }

        $this->waitingConnection = $connection;

        return [];
    }

    /**
     * Read the responses of the last flushed queue.
     *
     * @return array
     */
    public function wait()
    {
        $responses = array();
        $exceptions = $this->throwServerExceptions();

        while (!$this->waitingCommands->isEmpty()) {
            $command = $this->waitingCommands->dequeue();
            $response = $this->waitingConnection->readResponse($command);

            if (!$response instanceof ResponseInterface) {
                $responses[] = $command->parseResponse($response);
            } elseif ($response instanceof ErrorResponseInterface && $exceptions) {
                $this->exception($this->waitingConnection, $response);
            } else {
                $responses[] = $response;
            }
        }

        $this->waitingConnection = null;

        return $responses;
    }
}

    public function test_two_step_pipeline()
    {
        $shards = ['redis-0', 'redis-1', 'redis-2', 'redis-3', 'redis-4', 'redis-5', 'redis-6', 'redis-7'];
        $pipelines = [];
        //Write to all pipes
        foreach ($shards as $shard) {
            $pipeline = new TwoStepPipeline(Redis::connection($shard)->client());
            $pipeline->execute(function ($redis) {
                $redis->set('key1', 'value1');
                $redis->set('key2', 'value2');
            });
            $pipeline->execute(function ($redis) {
                $redis->set('key3', 'value3');
                $redis->set('key4', 'value4');
            });
            $pipelines[] = $pipeline;
        }
        // Wait for all the responses
        foreach ($pipelines as $pipeline) {
            $pipeline->wait();
        }
        foreach ($shards as $shard) {
            $this->assertEquals('value1', Redis::connection($shard)->get('key1'));
            $this->assertEquals('value2', Redis::connection($shard)->get('key2'));
            $this->assertEquals('value3', Redis::connection($shard)->get('key3'));
            $this->assertEquals('value4', Redis::connection($shard)->get('key4'));
        }
    }
```

**Describe alternatives you've considered**
I have sent a similar issue to another package php-redis-client, before I know predis support is back. I also don't know if my solution is currently possible to be implemented using phpredis extension. I also think using an event loop library for my problem is not necessary.

**Additional context**
In our production use-case, the commands to be run in parallel are some cpu-bound operations implemented by Redis modules API. For us, a map-reduce design was the only way to utilize the resources in order to minimize the time needed to process each request.

Thanks @tillkruss for supporting predis.

**Comment by tillkruss** [comment]
@nrk thoughts?

**Comment by nrk** [comment]
Hi @halaei,

Honestly I'm not exactly sure I undestand your use case and maybe I'm missing something but wouldn't it be possible to do the same already just by not passing a callback as the argument for `Predis\Client::pipeline()` in order to use the pipeline instance directly? Without any argument it returns a new pipeline instance which is not flushed unless `Predis\Pipeline\Pipeline::execute()` is explicitly invoked.

Just to re-use your snippet, it would look something like this:

```php
public function test_two_step_pipeline()
{
    $shards = ['redis-0', 'redis-1', 'redis-2', 'redis-3', 'redis-4', 'redis-5', 'redis-6', 'redis-7'];
    $pipelines = [];

    foreach ($shards as $shard) {
        $pipeline = Redis::connection($shard)->client()->pipeline();

        $pipeline->set('key1', 'value1');
        $pipeline->set('key2', 'value2');
        $pipeline->set('key3', 'value3');
        $pipeline->set('key4', 'value4');

        $pipelines[] = $pipeline;
    }

    foreach ($pipelines as $pipeline) {
        $pipeline->execute();
    }

    foreach ($shards as $shard) {
        $this->assertEquals('value1', Redis::connection($shard)->get('key1'));
        $this->assertEquals('value2', Redis::connection($shard)->get('key2'));
        $this->assertEquals('value3', Redis::connection($shard)->get('key3'));
        $this->assertEquals('value4', Redis::connection($shard)->get('key4'));
    }
}
```

**Comment by jimbonator** [comment]
I might be misreading the reporter's request, but I wonder if the I/O model they're envisioning looks something like this:

* write commands to shard A
* write commands to shard B
* write commands to shard C
* read responses from shard A
* read responses from shard B
* read responses from shard C

In the pipeline model, under-the-hood the I/O model is:

* write commands to shard A
* read responses from shard A
* write commands to shard B
* read responses from shard B
* write commands to shard C
* read responses from shard C

The problem is, `$pipeline->execute()` combines the read and write cycle, so processing multiple pipelines is serialized.

**Comment by halaei** [comment]
Assume I have 8 instances and each command takes 1 second on each instance to run. Using the current pipeline the total response time is 8 seconds, but using TwoStepPipeline assuming there are enough CPU cores and assuming Redis instances are not busy doing other tasks, it takes 1 second.

**Comment by halaei** [comment]
My code still is not efficient because the write and read operations are in blocking mode, so during I/O there is no parallelism.

**Comment by jimbonator** [comment]
> Please note that here by "async" I don't mean to work on top of some event loop library.

Do you mean that you would like non-blocking I/O with the calling code invoking some kind of `wait()` method that indicates I/O should occur, e.g.,

```
foreach ($shards as $shard) {
  $pipe = $shard->nonblocking();
  $pipe->ping();
  $pipe->ping();
  $pipe->ping();

  $pipes[] = $pipe;
}

Predis\Nonblocking::wait($pipes); // all reads and writes done here using nonblocking I/O to parallelize

foreach ($pipes as $pipe) {
  $responses = $pipe->responses();
}
```
(I'm just providing an example, not trying to formalize an API or anything.)

**Comment by halaei** [comment]
@jimbonator Yes exactly.

**Comment by nrk** [comment]
> I might be misreading the reporter's request, but I wonder if the I/O model they're envisioning looks something like this:

@jimbonator indeed, I missed the different behaviour compared to the current implementation of `Predis\Pipeline\Pipeline`. Sorry @halaei!

> My code still is not efficient because the write and read operations are in blocking mode, so during I/O there is no parallelism.

@halaei with Predis we can't do any better in terms of "efficiency" than what you already did, as the whole library is designed around blocking I/O. This considered and adding the fact that, at least to me, all of this seems to be quite specific to your use-case, I don't think such a feature would be a good candidate for inclusion into the library. We may try to make it easier to change the behaviour of `Predis\Pipeline\Pipeline` when extended by third-party code but we can't really turn it upside-down just for one limited use-case.

By the way if you don't actually need most of the features of `Predis\Pipeline\Pipeline` such as callbacks for automatic execution or intermediate flushes of the queued commands) then it would probably end up being a bit less cumbersome to roll your own class without extending `Predis\Pipeline\Pipeline` instead of trying to work around the limitations imposed by its design.

**Comment by halaei** [comment]
> By the way if you don't actually need most of the features of `Predis\Pipeline\Pipeline` such as callbacks for automatic execution or intermediate flushes of the queued commands, then it would probably end up being a bit less cumbersome to roll your own class without extending `Predis\Pipeline\Pipeline` instead of trying to work around the limitations imposed by its design.

Thanks @nrk for the suggestion. I take a look into it.

**Comment by jimbonator** [comment]
FWIW, I don't see this as a one-off or specific use-case request.  There's been times I've wished Predis offered an async mode, even if it meant _all_ requests with the client had to be handled that way.  (In particular, it would help with Redis pub/sub across multiple servers.)

That said, we don't use separate servers as shards, we configure `Predis\Client` for client-side sharding.

Even if there was no async mode, I still feel pipelines could be more efficiently handled with clusters by buffering writes (#586), flushing all sockets at once, and then reading back the responses.  It would create opportunities for parallelism, but not actually solve the problem @halaei is requesting.

**Comment by nrk** [comment]
@jimbonator I was reading about #586 just the other day but I still haven't replied due to the massive backlog, anyway I've found it quite interesting especially because I played with a similar idea a few years ago by reusing my [StringBuffer from Predis\Async](https://github.com/nrk/predis-async/blob/master/src/Connection/Buffer/StringBuffer.php).

As for a truly async mode in Predis, I'm not sure it'd be really feasible due to how the library is structured.
