### ISSUE TITLE
Future for Predis Async

### ISSUE THREAD

**Issue by crynobone** [predis/predis#645]
I hope the new Predis team will be able to also continue the development of <https://github.com/nrk/predis-async>. At the moment I been actively using a modified fork at <https://github.com/laravie/predis-async> with just add support to `reactphp/event-loop` v1+ where else `nrk/predis-async` only support v0.4. 

The package is extremely useful when you want to build realtime tool on top of Redis Subsub (e.g: websocket, daemon based data processing) using PHP and for my case (handling hundred of records per seconds).

**Comment by nrk** [comment]
Hi @crynobone,

We briefly discussed about [Predis\Async](https://github.com/nrk/predis-async) but there's currently no plan to continue its development here in the Predis organization, mostly because there's already a ton of work just for Predis and, adding to that, I think it'd probably better to use something like [reactphp-redis](https://github.com/clue/reactphp-redis) in a ReactPHP-based application because it perfectly integrates with its ecosystem as it uses promises and stuff. When Predis\Async was shaped and born ReactPHP didn't even have promises... well actually it hadn't even reach 0.1.0 when I started working on it back in early 2012, one of the first, if not the first, third-party library to depend on ReactPHP yay!

It's not intended to be definitive, but that's the plan at least for now.

I'm closing this issue basically because it's not directly related to Predis, but to be honest I don't want to dismiss the discussion so if it's about having Predis\Async up to date and you'd like to contribute some patches then we can still [keep on talking about it here](https://github.com/nrk/predis-async/issues).
