### ISSUE TITLE
Predis\Connection\ConnectionException: `AUTH` failed: ERR wrong number of arguments for 'auth' command

### ISSUE THREAD

**Issue by pesseyjulien** [predis/predis#664]
Receving the following error after upgrading to 1.1.6 :

 Predis\Connection\ConnectionException: `AUTH` failed: ERR wrong number of arguments for 'auth' command [redis://ec2-54-xx-164-xx.compute-1.amazonaws.com:17669]

Whereas my ENV variable is : 

redis://X:XX@ec2-54-158-164-114.compute-1.amazonaws.com:17669

What is wrong ?

Thanks in advance,
Julien

**Comment by nrk** [comment]
Hi @pesseyjulien,

What is the `X` that I see in the username portion of the userinfo fragment of your URI string?

I bet it's just placeholder with no real meaning. Until Predis 1.1.5 the username was ignored because Redis supported only a password-based authentication but with Redis 6.0 things changed with the introduction of ACL permissions which require both a username and a password for authentication, so now Predis uses the username (when supplied by the user) to fire an augmented `AUTH` command (`AUTH username password` instead of just `AUTH password`) which is not recognized by older versions of Redis.

From the [current README file](https://github.com/predis/predis/tree/v1.1.6#connecting-to-redis):

> Password protected servers can be accessed by adding password to the parameters set. When ACLs are enabled on Redis >= 6.0, both username and password are required for user authentication.

The [IANA document for the `redis://` scheme](http://www.iana.org/assignments/uri-schemes/prov/redis) clearly stated since the beginning that:

> If a future version of Redis adds support for multi-user authentication (e.g. if RCP1 gets accepted), it's suggested that the username to use when authenticating be obtained from the username portion of the "userinfo" URI field.

Meaning that you should not have populated the username with a placeholder value. Just omit any string for the username portion, it is still a valid URI: `redis://:YOURPASSWORD@ec2-54-158-164-114.compute-1.amazonaws.com:17669`

```
>>> Predis\Connection\Parameters::parse("redis://:YOURPASSWORD@ec2-54-158-164-114.compute-1.amazonaws.com:17669");
=> [
     "scheme" => "redis",
     "host" => "ec2-54-158-164-114.compute-1.amazonaws.com",
     "port" => 17669,
     "password" => "YOURPASSWORD",
   ]
```

**Comment by pesseyjulien** [comment]
Got it !

The X were placeholder indeed, to not display my username/password :) 

Thanks,
Julien

**Comment by mkopinsky** [comment]
I bumped into this when upgrading to predis >= 1.1.5. Heroku redis by default was setting the REDIS_URL environment variable of `redis://h:<password>@ec2-1-2-3-4.compute-1.amazonaws.com:17549` with a hardcoded (fake) username of `h`. I was able to temporarily get past it by editing the environment variable to remove the fake username, and permanently by deleting the Heroku Redis add-on and recreating it, which provisioned a Redis 6 instance with a REDIS_URL of `redis://:<password>@ec2-1-2-3-4.compute-1.amazonaws.com:10189`.
